# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'wfxr/tmux-fzf-url'
#set -g @plugin 'b0o/tmux-autoreload'

# Settings
set -g mouse on
set -g base-index 1
set -g focus-events on
setw -g pane-base-index 1
set-option -g history-limit 5000
set -g renumber-windows on
set -g set-clipboard on         
set -g status-position top
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -gq allow-passthrough all
set -g visual-activity off
set-option -g focus-events on

# Style settings
BG_COLOR="#1d2021"
TEXT_COLOR="#a69a81"
ACTIVE_COLOR="#a69a81"
INACTIVE_COLOR="#504945"
BLUE_COLOR="#7aaea2"

set -g status-position top
set -g status-style "bg=$BG_COLOR,fg=$TEXT_COLOR"
set -g status-left "#[fg=$ACCENT_COLOR,bold]  #S #[fg=$INACTIVE_COLOR]│ "
set -g window-status-format "#[fg=$INACTIVE_COLOR,bg=$BG_COLOR] #I:#W "
set -g window-status-current-format "#[fg=$ACTIVE_COLOR,bg=$BG_COLOR,bold] #I:#W*"
set -g window-status-separator ""
set -g pane-border-style "fg=$INACTIVE_COLOR"
set -g pane-active-border-style "fg=$ACTIVE_COLOR"
set -g message-style "bg=$BLUE_COLOR,fg=$BG_COLOR"
set -g message-command-style "bg=$BLUE_COLOR,fg=$BG_COLOR"
set -g mode-style "bg=$INACTIVE_COLOR,fg=$ACTIVE_COLOR"
set -g status-right ""

# Remap swap window
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# Remap prefix from 'C-b' to 'C-space'
unbind C-b
unbind C-Space
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Remap kill window fron C-& to C-k
unbind &
bind-key k kill-window

# Kill pane without confirmation
bind-key x kill-pane

# Split panes using h and v 
bind s split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Open a new window or pane in the current directory
bind c new-window -c "#{pane_current_path}"

# Reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# simpler window to show only sessions
unbind w
bind w choose-session
bind W choose-window

# Vim bindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Floating pane
bind P display-popup -w 80% -h 80% -d "#{pane_current_path}"

# Visual mode prefix + [
setw -g mode-keys vi
unbind-key -T copy-mode-vi v
bind-key -T copy-mode-vi 'v' send -X begin-selection     
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle 
bind-key -T copy-mode-vi 'y' send -X copy-selection     

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
